### ISSUE TITLE
[BUG] Invalid frequency error when converting origin

### ISSUE THREAD

**Issue by elvisnguyen007** [casact/chainladder-python#509]
**Describe the bug**

Setting the origin of the triangle to "OYDY" throws an error `ValueError: Invalid frequency: Y-JUL` in my code. When using the sample triangle, just loading the triangle also throws a similar error `ValueError: Invalid frequency: Y-DEC`. 

**To Reproduce**
Setting the origin of the triangle to "OYDY" throws an error.
```python
# Assume triangle has already been created from monthly level data
triangle = triangle.grain("OYDY", trailing=True)
```

Loading the sample triangle also throws a similar error. 
```python
import chainladder as cl
triangle = cl.load_sample('raa')
```

**Expected behavior**
The grain of the triangle should be converted to a year for both the origin and development. 

**Desktop (please complete the following information):**
 - Numpy Version [1.26.4]
 - Pandas Version [2.1.4]
 - Chainladder Version [0.8.19]

**Comment by jbogaardt** [comment]
This is a problem. Pandas is deprecating the 'A' frequency labeling in favor of 'Y'. The recent versions of pandas (>2.1, <2.2) does not support this, but pandas>=2.2.0 does. I think we need to do a patch release to support older versions of pandas.

**Comment by elvisnguyen007** [comment]
> This is a problem. Pandas is deprecating the 'A' frequency labeling in favor of 'Y'. The recent versions of pandas (>2.1, <2.2) does not support this, but pandas>=2.2.0 does. I think we need to do a patch release to support older versions of pandas.

Just to clarify for me, are you saying pandas (>2.1, <2.2) `does not` support 'Y' but in pandas >= 2.2.0 it `does` support 'Y'?

**Comment by jbogaardt** [comment]
> Just to clarify for me, are you saying pandas (>2.1, <2.2) `does not` support 'Y' but in pandas >= 2.2.0 it `does` support 'Y'?

Pandas supports both 'A' and 'Y' in 2.2 and later, but has a pesky deprecation warning regarding, so they've signaled their intent to eliminate 'A'. We really should support both versions since pandas still does and pandas<2.2 is still relatively new. I'm pushing a minor release `0.8.20` today for this.

**Comment by jbogaardt** [comment]
a patch has been issued and Pypi has chainladder==0.8.20.  I think this should resolve the issue.

**Comment by elvisnguyen007** [comment]
@jbogaardt Sorry finally got around to trying it out and the problem seems to still exist. I tried it with the same version of numpy and pandas but updated to the patched version 0.8.20.
